extends:
  - plugin:prettier/recommended
  - plugin:import/recommended
globals:
  __webpack_public_path__: true
  localStorage: false
  IS_EE: false
settings:
  import/resolver:
    - node:
        - extensions:
            - ".js"
            - ".ts"
        - moduleDirectory:
            - node_modules
            - src
parserOptions:
  parser: babel-eslint
  ecmaVersion: 6
  sourceType: module
  allowImportExportEverywhere: true
rules:
  no-dupe-args: error
  no-dupe-keys: error
  no-empty: error
  no-extra-semi: error
  no-irregular-whitespace: error
  no-unreachable: error
  consistent-return: error
  curly: error
  default-case: error
  eqeqeq:
    - error
    - always
  no-alert: error
  no-eval: error
  no-multi-spaces: error
  no-sequences: error
  no-unused-expressions: error
  no-useless-return: error
  no-with: error
  radix: error
  import/no-commonjs: error
  no-underscore-dangle: off
  import/no-unresolved: off
  no-else-return:
    - error
    - allowElseIf: true
  lines-between-class-members: off
  promise/always-return: off
  promise/no-callback-in-promise: off
  import/no-named-as-default: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      pathGroups:
        - pattern: ~/**
          group: internal
        - pattern: assets/**
          group: internal
        - pattern: common/**
          group: internal
        - pattern: helpers/**
          group: internal
        - pattern: utils/**
          group: internal
      alphabetize:
        order: asc
      newlines-between: always
overrides:
  - files:
      - '*.config.js'
      - '*.config.*.js'
    rules:
      import/no-extraneous-dependencies: off
      import/no-commonjs: off
      import/no-nodejs-modules: off
      filenames/match-regex: off
      no-console: off
